### ISSUE TITLE
Trying to access formats menu throws exception

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/kaitai#3]
After opening a file, if you click on the formats menu in the bottom right, it will not open, and complains that the ContextMenuManager C++ object has already been deleted. See highlighted log lines in screenshot.

![image](https://user-images.githubusercontent.com/41548458/111727349-1ca8ac00-8841-11eb-9240-524588e8a9bf.png)

**Comment by lwerdna** [comment]
Fixed in Kaitai plugin version 1.1.5.
