### ISSUE TITLE
Kaitai module parse error

### ISSUE THREAD

**Issue by johdcmlaker2000** [Vector35/kaitai#5]
Kaitai plugin didn't work

**To Reproduce**
1. Open any file, as an example PE exe
2. Select kaitai mode
3. Get "parseIo(): kaitai module microsoft_pe threw exception /types/mz_placeholder/seq/0: at pos 66: validation failed: not equal, expected b'MZ', but got b'\xba\x10', check file type" error

**Expected behavior**
Kaitai plugin wilkl parse file

**Screenshots**
![image](https://user-images.githubusercontent.com/95555363/146183010-7b7cfeed-50e2-47e2-8bcd-585a0f68553f.png)
![image](https://user-images.githubusercontent.com/95555363/146183033-ee42224b-9fe6-4edc-b294-f8dc3083700b.png)

**Version and Platform (required):**
 - Binja Version 2.4.2846 (Build ID df7c027e)
 - OS: Windows 10 Pro x64
 - Version 10.0.19042.1165

**Comment by shinmai** [comment]
FWIW, downgrading to plug-in version 1.1.1 (the last version prior to the kaitai 0.7 -> 0.9 update) is a workaround.

You obv don't get all the structs from the latter releases, but OTOH the plug-in seems to flat out not work with any of the later versions.

**Comment by lwerdna** [comment]
Fixed in Kaitai plugin version 1.1.5.
